//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fyp_groups_requests
    {
        public int group_id { get; set; }
        public int requested_by { get; set; }
        public int requested_to { get; set; }
    
        public virtual fyp_groups fyp_groups { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
