//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FYP_1_Grading
    {
        public int id { get; set; }
        public Nullable<int> std_id { get; set; }
        public string proj_comm_grade { get; set; }
        public string supervisor_grade { get; set; }
        public string document_comm_grade { get; set; }
        public string final_grade { get; set; }
    
        public virtual user user { get; set; }
    }
}
