//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meeting()
        {
            this.scheduled_meetings = new HashSet<scheduled_meetings>();
            this.uploaded_meeting_files = new HashSet<uploaded_meeting_files>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string meeting_notes { get; set; }
        public string location { get; set; }
        public string meeting_timing { get; set; }
        public Nullable<byte> isRecurring { get; set; }
        public Nullable<int> is_fyp_1 { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual status status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduled_meetings> scheduled_meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uploaded_meeting_files> uploaded_meeting_files { get; set; }
    }
}
