//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> msg_from { get; set; }
        public Nullable<int> msg_to { get; set; }
        public string file_path { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
