//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mybpms : DbContext
    {
        public Mybpms()
            : base("name=Mybpms")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_settings> app_settings { get; set; }
        public virtual DbSet<assigned_tasks> assigned_tasks { get; set; }
        public virtual DbSet<FYP_1_Grading> FYP_1_Grading { get; set; }
        public virtual DbSet<fyp_group_req_supervisor> fyp_group_req_supervisor { get; set; }
        public virtual DbSet<fyp_groups> fyp_groups { get; set; }
        public virtual DbSet<fyp_groups_requests> fyp_groups_requests { get; set; }
        public virtual DbSet<meeting> meetings { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<project_allocation> project_allocation { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<remark> remarks { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<scheduled_meetings> scheduled_meetings { get; set; }
        public virtual DbSet<status> statuses { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<uploaded_meeting_files> uploaded_meeting_files { get; set; }
        public virtual DbSet<uploaded_tasks> uploaded_tasks { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
