//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_allocation
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public int supervisor_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<byte> isSpringSemester { get; set; }
        public Nullable<int> allocation_year { get; set; }
        public Nullable<byte> isActive { get; set; }
    
        public virtual fyp_groups fyp_groups { get; set; }
        public virtual project project { get; set; }
        public virtual user user { get; set; }
    }
}
