//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remark
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> given_by { get; set; }
        public Nullable<int> given_to { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<byte> is_public { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual fyp_groups fyp_groups { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
