//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduled_meetings
    {
        public int id { get; set; }
        public int meeting_id { get; set; }
        public int scheduled_by { get; set; }
        public int scheduled_for { get; set; }
        public int status { get; set; }
        public Nullable<byte> is_attended { get; set; }
        public string meeting_timing { get; set; }
    
        public virtual meeting meeting { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual status status1 { get; set; }
    }
}
