//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.assigned_tasks = new HashSet<assigned_tasks>();
            this.uploaded_tasks = new HashSet<uploaded_tasks>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string task_deadline { get; set; }
        public Nullable<byte> isFinalTask { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<byte> is_fyp_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assigned_tasks> assigned_tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uploaded_tasks> uploaded_tasks { get; set; }
    }
}
