//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploaded_meeting_files
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public Nullable<int> supervisor_id { get; set; }
        public int meeting_id { get; set; }
        public string description { get; set; }
        public string file_path { get; set; }
    
        public virtual meeting meeting { get; set; }
        public virtual project project { get; set; }
        public virtual user user { get; set; }
    }
}
