//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitProjectProgessSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.assigned_tasks = new HashSet<assigned_tasks>();
            this.assigned_tasks1 = new HashSet<assigned_tasks>();
            this.FYP_1_Grading = new HashSet<FYP_1_Grading>();
            this.fyp_group_req_supervisor = new HashSet<fyp_group_req_supervisor>();
            this.fyp_group_req_supervisor1 = new HashSet<fyp_group_req_supervisor>();
            this.fyp_groups = new HashSet<fyp_groups>();
            this.fyp_groups_requests = new HashSet<fyp_groups_requests>();
            this.fyp_groups_requests1 = new HashSet<fyp_groups_requests>();
            this.messages = new HashSet<message>();
            this.messages1 = new HashSet<message>();
            this.project_allocation = new HashSet<project_allocation>();
            this.remarks = new HashSet<remark>();
            this.remarks1 = new HashSet<remark>();
            this.scheduled_meetings = new HashSet<scheduled_meetings>();
            this.scheduled_meetings1 = new HashSet<scheduled_meetings>();
            this.uploaded_meeting_files = new HashSet<uploaded_meeting_files>();
            this.uploaded_tasks = new HashSet<uploaded_tasks>();
            this.uploaded_tasks1 = new HashSet<uploaded_tasks>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string platform { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<double> cgpa { get; set; }
        public Nullable<int> is_allowed_in_meeting { get; set; }
        public string final_grade { get; set; }
        public string Pic { get; set; }
        public string fyp_1_final_grade { get; set; }
        public string fyp_2_final_grade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assigned_tasks> assigned_tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assigned_tasks> assigned_tasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FYP_1_Grading> FYP_1_Grading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fyp_group_req_supervisor> fyp_group_req_supervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fyp_group_req_supervisor> fyp_group_req_supervisor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fyp_groups> fyp_groups { get; set; }
        public virtual fyp_groups fyp_groups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fyp_groups_requests> fyp_groups_requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fyp_groups_requests> fyp_groups_requests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_allocation> project_allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remark> remarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remark> remarks1 { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduled_meetings> scheduled_meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduled_meetings> scheduled_meetings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uploaded_meeting_files> uploaded_meeting_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uploaded_tasks> uploaded_tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uploaded_tasks> uploaded_tasks1 { get; set; }
    }
}
